name: "Build & Tag"

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: Get next version
        id: version
        uses: technicallyjosh/next-version-action@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create Tag
        if: github.ref == 'refs/heads/main'
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.version.outputs.next_version }}
          tag_exists_error: false
          message: "Latest release"