name: "Build & Tag"

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get next version
        uses: MiguelRipoll23/get-next-version@v3.0.0
        id: get-next-version

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "${{ steps.get-next-version.outputs.next-version }}"
          tag_exists_error: false
          message: "Latest release"