name: "Build & Tag"

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get next version
        id: next-version
        uses: technote-space/get-next-version-action@v1

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "${process.env.NEXT_VERSION}"
          tag_exists_error: false
          message: "Latest release"